// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weather_forecast.data;

#nullable disable

namespace Weatherforecast.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221204173356_AddNewRowsAndTables")]
    partial class AddNewRowsAndTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Weather_forecast.Models.WFModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summaries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("humidity")
                        .HasColumnType("int");

                    b.Property<int>("pressure")
                        .HasColumnType("int");

                    b.Property<int>("temperature")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WFs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summaries = "Chilly",
                            humidity = 75,
                            pressure = 742,
                            temperature = 0
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summaries = "Bracing",
                            humidity = 78,
                            pressure = 743,
                            temperature = -1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summaries = "Bracing",
                            humidity = 82,
                            pressure = 744,
                            temperature = -3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summaries = "Freezing",
                            humidity = 79,
                            pressure = 746,
                            temperature = -5
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summaries = "Freezing",
                            humidity = 83,
                            pressure = 745,
                            temperature = -4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
